Added powershell here strings to powershell-restmethod codegen
postmanlabs/postman-code-generators pull request #395
Opened 2020-10-24 14:35 UTC by karmanya007

Fixes #322 .
Got rid of the escapes by using a [PowerShell here-strings](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-5.1#here-strings) in powershell-restmethod codegen.

2020-10-25 15:46 UTC, umeshp7 requested changes
@karmanya007 Can you add a sample output snippet with the new changes?
Also could you add/update unit tests?

2020-10-25 15:46 UTC, umeshp7 commented on codegens/js-xhr/npm-shrinkwrap.json
>    "lockfileVersion": 1,
Can we remove these changes from this PR?

2020-10-25 15:46 UTC, umeshp7 commented on codegens/nodejs-native/npm-shrinkwrap.json
>    "lockfileVersion": 1,
Can we remove these changes from this PR?

2020-10-25 15:46 UTC, umeshp7 commented on test/codegen/newman/fixtures/formdataFileCollection.json
> +              "src": "/mnt/c/Users/INVICTUS/Desktop/GSoC/postman-code-generators/dummyFile1.txt"
this should be `<file path>` There is a script which takes care of adding the path from the CI here.

2020-10-25 15:46 UTC, umeshp7 commented on test/codegen/newman/fixtures/formdataFileCollection.json
> +              "src": "/mnt/c/Users/INVICTUS/Desktop/GSoC/postman-code-generators/dummyBinaryFile"
this should be `<file path>` There is a script which takes care of adding the path from the CI here.

2020-10-25 16:43 UTC, karmanya007 reviewed
@umeshp7 Changes added.

2020-10-25 17:07 UTC, karmanya007 commented
@umeshp7 All checks have passed and I have added the sample outputs.

2020-10-26 05:19 UTC, Toronto00 approved these changes

2020-10-28 16:59 UTC, webholik commented
@karmanya007 I have enabled newman tests for poweshell codegen. These tests run the generated snippet in powershell and compare the output with that generated by newman. You can see in the [CI logs](https://travis-ci.com/github/postmanlabs/postman-code-generators/builds/194594824) that some of the tests are failing due to incorrect escaping of characters in the string. We have to get those tests to pass before we can merge your changes.

2020-10-28 17:11 UTC, karmanya007 commented
> @karmanya007 I have enabled newman tests for poweshell codegen. These tests run the generated snippet in powershell and compare the output with that generated by newman. You can see in the [CI logs](https://travis-ci.com/github/postmanlabs/postman-code-generators/builds/194594824) that some of the tests are failing due to incorrect escaping of characters in the string. We have to get those tests to pass before we can merge your changes.

@webholik On it!

2020-11-03 06:57 UTC, umeshp7 commented
@karmanya007 Any updates here? Looks like there are some conflicts.

2020-11-03 09:21 UTC, karmanya007 commented
@umeshp7 Had a marriage in my family so I was not active as much. I know the fix. Just have to implement it. Will do so shortly.

2020-11-13 11:41 UTC, karmanya007 commented
Getting these three errors. @Toronto00 , @umeshp7 Could you guide me in the correct direction on how to approach these conflicts.
![1](https://user-images.githubusercontent.com/24437967/99068794-2db38900-25d3-11eb-9279-125b0fed6f51.jpg)
![2](https://user-images.githubusercontent.com/24437967/99068798-3015e300-25d3-11eb-8854-f4c82b7d69c8.jpg)
![3](https://user-images.githubusercontent.com/24437967/99068801-3310d380-25d3-11eb-9f24-67ecc346b17a.jpg)

2020-11-15 08:18 UTC, karmanya007 commented
@webholik Are the 1stand 3rd error from wrong newman tests, maybe?

2020-11-17 09:34 UTC, webholik commented
@karmanya007 1st error is because you are not escaping `$` character in the output string. If `$` is present in a string then Powershell tries to replace it with a variable. In this case it is replacing it with the value of `$test`, which isn't defined, so it is just putting empty string here.

2nd error again is just wrong escaping. `` ` `` character must be properly escaped.

3rd has been fixed in #421. You should [rebase](https://docs.github.com/en/free-pro-team@latest/github/using-git/about-git-rebase) your PR on top of it.

2023-03-28 10:43 UTC, dhwaneetbhatt commented
@karmanya007 We recently pushed changes to use here-strings in Powershell. Could you check if this PR would still be required?

2024-09-25 08:15 UTC, closed without merging