Feature/r httr
postmanlabs/postman-code-generators pull request #602
Opened 2022-03-31 00:46 UTC by erfemega

Adding r-httr codegenerator

2022-03-31 22:39 UTC, LuisTejedaS requested changes
You are missing test for options e.g. how do you know that time out snippet is present

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/README.md
> +The module will expose an object which will have property `convert` which is the function for converting the Postman-SDK request to swift code snippet.
This should say to r code snippet instead of swift code

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/lib/rHttr.js
> +  // mapToSnippetArray = groupHeadersSameKey(mapToSnippetArray);
You may forget to add the group headers or this commented line is no longer needed

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/lib/rHttr.js
> +  return snippetRequest;
What about other verbs like options head etc.

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/lib/util/parseBody.js
> +    // bodySnippet += `"${sanitizeString(body.toString(), bodyTrim)}"`;
This line is no longer needed we can remove it

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/lib/util/parseBody.js
> +  // let name = `${indentation.repeat(2)}[\n${indentation.repeat(3)}` +
This code is no longer needed

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/npm/test.js
> +  // require('./test-unit')
We should be running unit testing when we run npm run test in your folder

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/package.json
> +  "description": "Converts Postman SDK Requests to swift code snippet",
Change swift for r  or r-httr

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/package.json
> +    "test-newman": "node npm/test-newman.js"
missing test unit command?

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +  // sdk = require('postman-collection'),
Unnecessary commented code

2022-03-31 22:39 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +  // it('should convert a simple get request', function (done) {
This test is comented

2022-04-04 18:17 UTC, LuisTejedaS requested changes
Some code still commented

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // collection.items.members.forEach((item) => {
unnecessary  commented line

2022-04-04 18:17 UTC, LuisTejedaS commented on codegens/r-httr/test/unit/convert.test.js
> +    // });
unnecessary  commented line

2022-04-04 21:06 UTC, LuisTejedaS approved these changes
LGTM

2022-04-05 03:38 UTC, erfemega commented
Hi @umeshp7 I add some screenshots from the generated code:
Rquest headers with special characters:
![image](https://user-images.githubusercontent.com/19155973/161670323-f01c0b6e-23f9-4988-8f26-a5b0feca0c9f.png)

Request Headers:
![image](https://user-images.githubusercontent.com/19155973/161670445-87f75062-23ed-403e-b9e3-b507b780da2b.png)

Request headers with disabled headers:
![image](https://user-images.githubusercontent.com/19155973/161670590-ac2cc07f-4a70-4f12-a1b2-051c5cb0ae83.png)

GET Request with disabled query:
![image](https://user-images.githubusercontent.com/19155973/161670687-816bbab7-7d4e-4e43-9aa4-0bc1ba5785b6.png)

POST Raw text:
![image](https://user-images.githubusercontent.com/19155973/161670791-981e2421-dfc4-42f7-997e-7e2cf8151e7e.png)

POST json with raw:
![image](https://user-images.githubusercontent.com/19155973/161671066-7f8358ca-775f-4ee9-ade7-954e9ca547cd.png)

POST GraphQL:
![image](https://user-images.githubusercontent.com/19155973/161672775-91fb1e80-fc34-4c3b-a961-27b7125a786d.png)

Javascript with Raw:
![image](https://user-images.githubusercontent.com/19155973/161672943-5768b9e3-c94a-4a1a-b170-832aa1687a3e.png)

Text/Xml with raw:
![image](https://user-images.githubusercontent.com/19155973/161673051-26ffdaf9-e506-4b8a-8a77-5e10fa597401.png)

POST Url encoded data:
![image](https://user-images.githubusercontent.com/19155973/161673261-d221a426-edd8-4f56-842e-1a8278ec77fd.png)

PUT Request:
![image](https://user-images.githubusercontent.com/19155973/161673368-462b9c99-224f-4337-a133-2769e4e91251.png)

PATCH Request:
![image](https://user-images.githubusercontent.com/19155973/161673447-2c427199-4a45-4616-a677-aa5898cc071c.png)

DELETE Request:
![image](https://user-images.githubusercontent.com/19155973/161673530-037af112-b12c-4a90-a23e-4b34ee295c95.png)

Post empty form data:
![image](https://user-images.githubusercontent.com/19155973/161673591-5d52684c-f018-4e48-8126-50a178f9ad5e.png)

POST Multipart/form-data with text parameters:
![image](https://user-images.githubusercontent.com/19155973/161673770-4cb803ee-b1ac-4201-8991-a72f8b93c6c0.png)

Single/multiple file load via form-data:
![image](https://user-images.githubusercontent.com/19155973/161673947-07093f0d-a990-4834-9406-b69590d83797.png)

Binary file upload via form data:
![image](https://user-images.githubusercontent.com/19155973/161674046-bd875a80-98e9-4b76-b36b-30004904da26.png)

Multiple headers with same value:
![image](https://user-images.githubusercontent.com/19155973/161674104-334960e1-6945-4221-8d0e-a741540a668f.png)

2022-04-06 06:30 UTC, webholik commented
![image]( https://user-images.githubusercontent.com/19155973/161673770-4cb803ee-b1ac-4201-8991-a72f8b93c6c0.png)
@erfemega Can you fix the text alignment in line number 3 in the above image. `'pl' = '\'a\''` should be aligned with the next line `'qu' = '"b"'`.

2022-04-06 08:53 UTC, umeshp7 commented
Also we need appropriate spacing. For example: 
![snippet-r](https://user-images.githubusercontent.com/31915995/161935522-31986c8e-4fd4-43ad-b6cf-48729b8460e2.png)

Here the spacing should be something like this:

```
library(httr)

body = list(
    'pl' = 'a'
)

res <- VERB(...)

cat(content())
```

This way its a bit more readable.

2022-04-06 19:27 UTC, erfemega commented
Sure @webholik it was my mistake when I was copying the snippets, the generated snippet does not have this issue.
Done @umeshp7 
I've edited my last comment with the right snippets.
Thank you

2022-04-18 11:40 UTC, merged