[FIX] cURL code snippet contains encoded value for special char + instead of char itself
postmanlabs/postman-code-generators pull request #735
Opened 2024-04-30 08:19 UTC by aman-v-singh

2024-04-30 10:23 UTC, VShingala requested changes
Let's add unit tests for the change before requesting review.

2024-04-30 10:41 UTC, VShingala commented on codegens/curl/lib/util.js
> +      .replace(/%2B/g, '+');
@aman-v-singh Let's keep this at line no. 228. i.e. before we replace `%` chars.

2024-04-30 10:54 UTC, aman-v-singh commented
I included this change in the test and it is passing

<img width="886" alt="Screenshot 2024-04-30 at 4 21 10 PM" src="https://github.com/postmanlabs/postman-code-generators/assets/121886615/63dea194-07ab-4a64-ab31-79290df439ca">

2024-04-30 12:36 UTC, VShingala approved these changes
@aman-v-singh I think changes looks good. Let's make sure we test this behaviour in app as well before making a release.

2024-05-01 05:13 UTC, VShingala approved these changes

2024-05-02 03:04 UTC, merged